package com.wayto.android.map.greedao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        MapLayer1Dao.createTable(db, ifNotExists);
        MapLayer2Dao.createTable(db, ifNotExists);
        MapLayer3Dao.createTable(db, ifNotExists);
        MapLayer4Dao.createTable(db, ifNotExists);
        MapLayer5Dao.createTable(db, ifNotExists);
        MapLayer6Dao.createTable(db, ifNotExists);
        MapLayer7Dao.createTable(db, ifNotExists);
        MapLayer8Dao.createTable(db, ifNotExists);
        MapLayer9Dao.createTable(db, ifNotExists);
        MapLayer10Dao.createTable(db, ifNotExists);
        MapLayer11Dao.createTable(db, ifNotExists);
        MapLayer12Dao.createTable(db, ifNotExists);
        MapLayer13Dao.createTable(db, ifNotExists);
        MapLayer14Dao.createTable(db, ifNotExists);
        MapLayer15Dao.createTable(db, ifNotExists);
        MapLayer16Dao.createTable(db, ifNotExists);
        MapLayer17Dao.createTable(db, ifNotExists);
        MapLayer18Dao.createTable(db, ifNotExists);
        MapLayer19Dao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        MapLayer1Dao.dropTable(db, ifExists);
        MapLayer2Dao.dropTable(db, ifExists);
        MapLayer3Dao.dropTable(db, ifExists);
        MapLayer4Dao.dropTable(db, ifExists);
        MapLayer5Dao.dropTable(db, ifExists);
        MapLayer6Dao.dropTable(db, ifExists);
        MapLayer7Dao.dropTable(db, ifExists);
        MapLayer8Dao.dropTable(db, ifExists);
        MapLayer9Dao.dropTable(db, ifExists);
        MapLayer10Dao.dropTable(db, ifExists);
        MapLayer11Dao.dropTable(db, ifExists);
        MapLayer12Dao.dropTable(db, ifExists);
        MapLayer13Dao.dropTable(db, ifExists);
        MapLayer14Dao.dropTable(db, ifExists);
        MapLayer15Dao.dropTable(db, ifExists);
        MapLayer16Dao.dropTable(db, ifExists);
        MapLayer17Dao.dropTable(db, ifExists);
        MapLayer18Dao.dropTable(db, ifExists);
        MapLayer19Dao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(MapLayer1Dao.class);
        registerDaoClass(MapLayer2Dao.class);
        registerDaoClass(MapLayer3Dao.class);
        registerDaoClass(MapLayer4Dao.class);
        registerDaoClass(MapLayer5Dao.class);
        registerDaoClass(MapLayer6Dao.class);
        registerDaoClass(MapLayer7Dao.class);
        registerDaoClass(MapLayer8Dao.class);
        registerDaoClass(MapLayer9Dao.class);
        registerDaoClass(MapLayer10Dao.class);
        registerDaoClass(MapLayer11Dao.class);
        registerDaoClass(MapLayer12Dao.class);
        registerDaoClass(MapLayer13Dao.class);
        registerDaoClass(MapLayer14Dao.class);
        registerDaoClass(MapLayer15Dao.class);
        registerDaoClass(MapLayer16Dao.class);
        registerDaoClass(MapLayer17Dao.class);
        registerDaoClass(MapLayer18Dao.class);
        registerDaoClass(MapLayer19Dao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
